### ISSUE TITLE
New endpoint to get woo order statuses

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/wc-api-dev#115]
There is a generic post status API available, so this one would be lower priority. It would just be nice to not have to pull all the post statuses and then filter out by just the ones prefixed with 'wc-`.

Ideally the results would provide enough information so we know which ones are custom and which ones are core. An example of a result may look like this:

```
data: [{
	"id":1,
	"status":"processing",
	"label":"Processing",
	"is_core":true
},{
	"id": 200,
	"status":"wc-gold",
	"label":"Gold Status",
	"is_core":false,
	"created_by":{
		{
		  "type": "plugin",
		  "name": "WooCommerce",
		  "url": "https://woocommerce.com/",
		  "author_name": "Automattic"
		}
	}
}]
```

I'm still learning about all that's available so if anything crucial is missing or something doesn't make sense, feel free to add or change as necessary.

**Comment by aforcier** [comment]
As @claudiosanches pointed out, we can get a list of valid order statuses via `OPTIONS /wc/v2/orders/`, but unfortunately this only returns the slugs and only solves part of the problem.

The main use case for an order status endpoint for Woo mobile would be to obtain the display names for each status when displaying them in the UI (also having a core vs not flag would be a bonus).

(Still low priority as @AmandaRiu pointed out since we can extract the necessary things from the `/wp/v2/statuses` endpoint and filter only `wc-` statuses, but a core endpoint would be neater/more reliable.)

**Comment by claudiosanches** [comment]
Should be covered by https://github.com/woocommerce/woocommerce/pull/21306
Using `GET /wp-json/wc/v3/reports/orders/totals`, will return the total of orders with each status, also include slug and name of each status.

@aforcier can you please test WooCommerce 3.5.0 Beta 1 and check if this helps for your user case?

**Comment by aforcier** [comment]
@claudiosanches gave it a whirl, it looks like `GET /wp-json/wc/v3/reports/orders/totals` will work for us, thank you 👍

I found one thing that surprised me I wanted to ask about - I noticed the list of statuses returned from this endpoint include the `wc-` prefix with which they're stored in the database as post statuses:

```js
[
  {
    "slug": "wc-pending",
    "name": "Pending payment",
    "total": 0
  },
  {
    "slug": "wc-processing",
    "name": "Processing",
    "total": 3
  },
  {
    "slug": "wc-on-hold",
    "name": "On hold",
    "total": 3
  },
  {
    "slug": "wc-completed",
    "name": "Completed",
    "total": 0
  },
  {
    "slug": "wc-cancelled",
    "name": "Cancelled",
    "total": 1
  },
  {
    "slug": "wc-refunded",
    "name": "Refunded",
    "total": 0
  },
  {
    "slug": "wc-failed",
    "name": "Failed",
    "total": 0
  }
]
```

However, the rest of the WC API endpoints (at least the v2 ones I've interacted with) strip the prefix. For example, order objects returned from the API have the status as `processing` instead of `wc-processing` - and that's also the expected format when filtering by status in the `wc/v3/orders` endpoint (as well as what we get if we call `OPTIONS /wc/v3/orders/`). Is this difference intentional?

**Comment by aforcier** [comment]
Also, sorry if this is already a known issue, but I happened to notice that the base `/wc/v3/reports` endpoint seems to be declaring a different set of endpoints which don't actually exist (I take it `count` was renamed to `totals`?).

GET `/wc/v3/reports/`:

```js
[
  ...
  {
    "slug": "orders\/count",
    "description": "Orders stats count.",
    "_links": {
      "self": [
        {
          "href": "http:\/\/site\/wp-json\/wc\/v3\/reports\/orders\/count"
        }
      ],
      "collection": [
        {
          "href": "http:\/\/site\/wp-json\/wc\/v3\/reports"
        }
      ]
    }
  },
  ...
  }
]
```

The endpoints are correctly listed in response to the top-level `GET /wc/v3/` though.

**Comment by claudiosanches** [comment]
@aforcier thanks, I'll fix it.

**Comment by claudiosanches** [comment]
This should solve all issues here: https://github.com/woocommerce/woocommerce/pull/21384
