### ISSUE TITLE
Make "is_paying_customer", "orders_count" and "total_spent" optional on Customers endpoint

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/wc-api-dev#53]
```
is_paying_customer | bool | Is the customer a paying customer? READ-ONLY
orders_count | integer | Quantity of orders made by the customer. READ-ONLY
total_spent | string | Total amount spent. READ-ONLY
```

All those fields require heavy queries on the database, so making optional should improve a lot the performance of the customers endpoint.

Ref: https://github.com/woocommerce/woocommerce/issues/16946

**Comment by peterfabian** [comment]
@claudiosanches 
This maybe needs a decision on how to request which fields to include, it seems like there are more options, e.g.: 
- LinkedIn way: `/people:(id,first-name,last-name,industry)`
- Facebook way: `/friends?fields=id,name,picture`
- Google way: `?fields=title,media:group(media:thumbnail)`

Once the decision is made, we should look into how to implement this, if this should be possible across all the endpoints (as I assume we don't want to just enable it for 1 route).

**Comment by peterfabian** [comment]
Another (easier) option mentioned by Claudio is to use a special path for those, e.g.:
`/customers/<id>/is_paying_customer`.

**Comment by peterfabian** [comment]
I actually spent some time today implementing these new paths, but after some more thought, I'm wondering--shouldn't we just include those in the new `reports` endpoint instead of 
- `/customers/<id>/total_spent`
- `/customers/<id>/orders_count`
?

Also, `is_paying_customer` is fetched when the customer object is created, so I don't think it needs to be removed.

**Comment by claudiosanches** [comment]
@peterfabian makes sense move it to the new `reports` endpoint, feel free to close it.
