### ISSUE TITLE
Change "title" to "name" in category image

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/wc-api-dev#6]
I forget to fix the category image name, just updated the schema and now we need to fix it for v3.

**Comment by ajayghaghretiya** [comment]
Hello, I have found this in "class-wc-rest-product-categories-controller.php" file but I am confusing how to contribute here because "class-wc-rest-dev-product-categories-controller.php" is extend class from the woocommerce/includes/api/class-wc-rest-product-categories-controller.php file.

And I have not found same code in this file "class-wc-rest-dev-product-categories-controller.php"

So How can I contribute here...
Please suggest.

**Comment by claudiosanches** [comment]
Closed in https://github.com/woocommerce/woocommerce/pull/20115
